import type { NavItem, Role } from './types';

export const navConfig: Record<Role, NavItem[]> = {
  'super-admin': [
    { title: 'Dashboard', href: '/super-admin/dashboard', icon: 'LayoutDashboard' },
    { title: 'Tenants', href: '/super-admin/tenants', icon: 'Building2' },
    { title: 'Subscriptions & Billing', href: '/super-admin/billing', icon: 'CreditCard' },
    { title: 'Plans & Pricing', href: '/super-admin/plans', icon: 'Tags' },
    { title: 'Feature Flags', href: '/super-admin/feature-flags', icon: 'Flag' },
    { title: 'Support Tickets', href: '/super-admin/support', icon: 'LifeBuoy' },
    { title: 'Platform Analytics', href: '/super-admin/analytics', icon: 'BarChart3' },
    { title: 'Audit Logs', href: '/super-admin/audit-logs', icon: 'ScrollText' },
    { title: 'Announcements', href: '/super-admin/announcements', icon: 'Megaphone' },
    { title: 'Settings', href: '/super-admin/settings', icon: 'Settings' },
  ],
  admin: [
    { title: 'Dashboard', href: '/admin/dashboard', icon: 'LayoutDashboard' },
    {
      title: 'Organization',
      href: '/admin/organization',
      icon: 'Network',
      children: [
        { title: 'Company Profile', href: '/admin/organization/company-profile', icon: 'Building2' },
        { title: 'Org Chart', href: '/admin/organization/org-chart', icon: 'GitFork' },
        { title: 'Departments', href: '/admin/organization/departments', icon: 'Boxes' },
        { title: 'Designations', href: '/admin/organization/designations', icon: 'BadgeCheck' },
        { title: 'Locations', href: '/admin/organization/locations', icon: 'MapPin' },
        { title: 'Holiday Calendar', href: '/admin/organization/holidays', icon: 'CalendarDays' },
        { title: 'Policies', href: '/admin/organization/policies', icon: 'FileText' },
        { title: 'Roles & Permissions', href: '/admin/organization/roles', icon: 'ShieldCheck' },
      ],
    },
    {
      title: 'People',
      href: '/admin/people',
      icon: 'Users',
      children: [
        { title: 'Directory', href: '/admin/people', icon: 'Contact' },
        { title: 'Add Employee', href: '/admin/people/add', icon: 'UserPlus' },
        { title: 'Bulk Import', href: '/admin/people/bulk-import', icon: 'Upload' },
        { title: 'Offboarding', href: '/admin/people/offboarding', icon: 'LogOut' },
        { title: 'Documents', href: '/admin/people/documents', icon: 'FolderArchive' },
        { title: 'Lifecycle', href: '/admin/people/lifecycle', icon: 'Activity' },
        { title: 'Probation', href: '/admin/people/probation', icon: 'Hourglass' },
        { title: 'Transfers', href: '/admin/people/transfers', icon: 'ArrowLeftRight' },
      ],
    },
    {
      title: 'Attendance & Leave',
      href: '/admin/attendance',
      icon: 'CalendarCheck',
      children: [
        { title: 'Attendance Dashboard', href: '/admin/attendance', icon: 'CalendarCheck' },
        { title: 'Attendance Log', href: '/admin/attendance/log', icon: 'ListChecks' },
        { title: 'Shifts', href: '/admin/attendance/shifts', icon: 'Clock' },
        { title: 'Regularization', href: '/admin/attendance/regularization', icon: 'RefreshCw' },
        { title: 'Leave Dashboard', href: '/admin/leave', icon: 'CalendarOff' },
        { title: 'Leave Policy', href: '/admin/leave/policy', icon: 'BookOpen' },
        { title: 'Leave Approvals', href: '/admin/leave/approvals', icon: 'CheckSquare' },
        { title: 'Leave Balances', href: '/admin/leave/balances', icon: 'Scale' },
        { title: 'Holidays', href: '/admin/leave/holidays', icon: 'CalendarDays' },
        { title: 'Timesheets', href: '/admin/attendance/timesheets', icon: 'Timer' },
        { title: 'Overtime', href: '/admin/attendance/overtime', icon: 'ClockAlert' },
      ],
    },
    {
      title: 'Payroll',
      href: '/admin/payroll',
      icon: 'Banknote',
      children: [
        { title: 'Dashboard', href: '/admin/payroll', icon: 'Banknote' },
        { title: 'Run Payroll', href: '/admin/payroll/run', icon: 'PlayCircle' },
        { title: 'Salary Structures', href: '/admin/payroll/structures', icon: 'Layers' },
        { title: 'Salary Assignment', href: '/admin/payroll/assignment', icon: 'UserCog' },
        { title: 'Payslips', href: '/admin/payroll/payslips', icon: 'ReceiptText' },
        { title: 'Reimbursements', href: '/admin/payroll/reimbursements', icon: 'Receipt' },
        { title: 'Loans & Advances', href: '/admin/payroll/loans', icon: 'HandCoins' },
        { title: 'Compliance', href: '/admin/payroll/compliance', icon: 'Landmark' },
        { title: 'Tax Declaration', href: '/admin/payroll/tax', icon: 'FileSpreadsheet' },
        { title: 'Full & Final', href: '/admin/payroll/full-final', icon: 'Scale' },
        { title: 'Reports', href: '/admin/payroll/reports', icon: 'BarChart3' },
        { title: 'Compensation', href: '/admin/payroll/compensation', icon: 'Coins' },
      ],
    },
    {
      title: 'Performance',
      href: '/admin/performance',
      icon: 'TrendingUp',
      children: [
        { title: 'Goals / OKR', href: '/admin/performance', icon: 'Target' },
        { title: 'Review Cycles', href: '/admin/performance/reviews', icon: 'Repeat' },
        { title: '9-Box Grid', href: '/admin/performance/calibration', icon: 'LayoutGrid' },
        { title: 'Feedback Wall', href: '/admin/performance/feedback', icon: 'MessageSquareHeart' },
        { title: '1:1 Meetings', href: '/admin/performance/one-on-ones', icon: 'MessagesSquare' },
        { title: 'Reports', href: '/admin/performance/reports', icon: 'BarChart3' },
      ],
    },
    {
      title: 'Hiring',
      href: '/admin/hiring',
      icon: 'Briefcase',
      children: [
        { title: 'Dashboard', href: '/admin/hiring', icon: 'Briefcase' },
        { title: 'Requisitions', href: '/admin/hiring/requisitions', icon: 'FilePlus' },
        { title: 'Job Postings', href: '/admin/hiring/postings', icon: 'Megaphone' },
        { title: 'Pipeline', href: '/admin/hiring/pipeline', icon: 'KanbanSquare' },
        { title: 'Interviews', href: '/admin/hiring/interviews', icon: 'CalendarClock' },
        { title: 'Offers', href: '/admin/hiring/offers', icon: 'FileSignature' },
        { title: 'Referrals', href: '/admin/hiring/referrals', icon: 'Share2' },
      ],
    },
    {
      title: 'Helpdesk',
      href: '/admin/helpdesk',
      icon: 'LifeBuoy',
      children: [
        { title: 'Dashboard', href: '/admin/helpdesk', icon: 'LifeBuoy' },
        { title: 'All Tickets', href: '/admin/helpdesk/tickets', icon: 'Ticket' },
        { title: 'Categories & SLA', href: '/admin/helpdesk/categories', icon: 'Settings2' },
        { title: 'Knowledge Base', href: '/admin/helpdesk/knowledge-base', icon: 'BookMarked' },
      ],
    },
    {
      title: 'Assets',
      href: '/admin/assets',
      icon: 'Laptop',
      children: [
        { title: 'Inventory', href: '/admin/assets', icon: 'Boxes' },
        { title: 'Requests', href: '/admin/assets/requests', icon: 'PackagePlus' },
      ],
    },
    {
      title: 'Expenses',
      href: '/admin/expenses',
      icon: 'Wallet',
      children: [
        { title: 'Dashboard', href: '/admin/expenses', icon: 'Wallet' },
        { title: 'Approvals', href: '/admin/expenses/approvals', icon: 'CheckSquare' },
        { title: 'Policy & Categories', href: '/admin/expenses/policy', icon: 'BookOpen' },
      ],
    },
    {
      title: 'Learning',
      href: '/admin/learning',
      icon: 'GraduationCap',
      children: [
        { title: 'Courses', href: '/admin/learning', icon: 'BookOpen' },
        { title: 'Assign Training', href: '/admin/learning/assign', icon: 'UserPlus' },
        { title: 'Progress', href: '/admin/learning/progress', icon: 'TrendingUp' },
      ],
    },
    {
      title: 'Engagement',
      href: '/admin/engagement',
      icon: 'Heart',
      children: [
        { title: 'Announcements', href: '/admin/engagement', icon: 'Megaphone' },
        { title: 'Surveys', href: '/admin/engagement/surveys', icon: 'BarChart3' },
        { title: 'Recognition', href: '/admin/engagement/recognition', icon: 'Award' },
        { title: 'Events', href: '/admin/engagement/events', icon: 'PartyPopper' },
        { title: 'Polls', href: '/admin/engagement/polls', icon: 'Vote' },
      ],
    },
    {
      title: 'Reports',
      href: '/admin/reports',
      icon: 'BarChart3',
      children: [
        { title: 'Report Builder', href: '/admin/reports', icon: 'Wrench' },
        { title: 'Library', href: '/admin/reports/library', icon: 'Library' },
        { title: 'Analytics', href: '/admin/reports/analytics', icon: 'PieChart' },
      ],
    },
    {
      title: 'Settings',
      href: '/admin/settings',
      icon: 'Settings',
      children: [
        { title: 'General', href: '/admin/settings', icon: 'Settings' },
        { title: 'Notifications', href: '/admin/settings/notifications', icon: 'Bell' },
        { title: 'Integrations', href: '/admin/settings/integrations', icon: 'Puzzle' },
        { title: 'Billing', href: '/admin/settings/billing', icon: 'CreditCard' },
        { title: 'Data Export', href: '/admin/settings/export', icon: 'Download' },
        { title: 'Custom Fields', href: '/admin/settings/custom-fields', icon: 'Brackets' },
        { title: 'Approvals', href: '/admin/settings/approvals', icon: 'Workflow' },
      ],
    },
  ],
  'hr-manager': [
    { title: 'Dashboard', href: '/hr-manager/dashboard', icon: 'LayoutDashboard' },
    { title: 'People', href: '/hr-manager/people', icon: 'Users' },
    { title: 'Leave Approvals', href: '/hr-manager/leave-approvals', icon: 'CheckSquare' },
    { title: 'Attendance', href: '/hr-manager/attendance', icon: 'CalendarCheck' },
    { title: 'Payroll', href: '/hr-manager/payroll', icon: 'Banknote' },
    { title: 'Performance', href: '/hr-manager/performance', icon: 'TrendingUp' },
    { title: 'Engagement', href: '/hr-manager/engagement', icon: 'Heart' },
    { title: 'Helpdesk', href: '/hr-manager/helpdesk', icon: 'LifeBuoy' },
    { title: 'Reports', href: '/hr-manager/reports', icon: 'BarChart3' },
  ],
  manager: [
    { title: 'Dashboard', href: '/manager/dashboard', icon: 'LayoutDashboard' },
    { title: 'My Team', href: '/manager/team', icon: 'Users' },
    { title: 'Approvals', href: '/manager/approvals', icon: 'CheckSquare', badge: '4' },
    { title: 'Team Performance', href: '/manager/performance', icon: 'TrendingUp' },
    { title: 'Team Attendance', href: '/manager/attendance', icon: 'CalendarCheck' },
    { title: 'Give Feedback', href: '/manager/feedback', icon: 'MessageSquareHeart' },
  ],
  employee: [
    { title: 'Dashboard', href: '/employee/dashboard', icon: 'LayoutDashboard' },
    { title: 'My Profile', href: '/employee/profile', icon: 'UserRound' },
    { title: 'Attendance', href: '/employee/attendance', icon: 'CalendarCheck' },
    {
      title: 'Leave',
      href: '/employee/leave',
      icon: 'CalendarOff',
      children: [
        { title: 'Apply Leave', href: '/employee/leave/apply', icon: 'Plus' },
        { title: 'My Balance', href: '/employee/leave/balance', icon: 'Scale' },
      ],
    },
    {
      title: 'Payroll',
      href: '/employee/payslips',
      icon: 'Banknote',
      children: [
        { title: 'Payslips', href: '/employee/payslips', icon: 'ReceiptText' },
        { title: 'Tax Declaration', href: '/employee/tax', icon: 'FileSpreadsheet' },
        { title: 'Reimbursements', href: '/employee/reimbursements', icon: 'Receipt' },
      ],
    },
    { title: 'Performance', href: '/employee/performance', icon: 'TrendingUp' },
    { title: 'Helpdesk', href: '/employee/helpdesk', icon: 'LifeBuoy' },
    { title: 'My Assets', href: '/employee/assets', icon: 'Laptop' },
    { title: 'Expenses', href: '/employee/expenses', icon: 'Wallet' },
    { title: 'Learning', href: '/employee/learning', icon: 'GraduationCap' },
    { title: 'Directory', href: '/employee/directory', icon: 'Contact' },
    { title: 'Announcements', href: '/employee/announcements', icon: 'Megaphone' },
    { title: 'My Documents', href: '/employee/documents', icon: 'FolderArchive' },
    { title: 'Request Letter', href: '/employee/request-letter', icon: 'FileSignature' },
  ],
};
